### ISSUE TITLE
translate_to_xdg() called with False

### ISSUE THREAD

**Issue by smathot** [dschreij/fileinspector#2]
I encountered this crash in OpenSesame. It appears to result from a bug in `determine_type()` that calls `translate_to_xdg()` with `False`:

``` .python
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/libqtopensesame/widgets/tree_overview.py", line 756, in dropEvent
    self.main_window.open_file(path=data[u'url'])
  File "/usr/lib/python2.7/dist-packages/libqtopensesame/qtopensesame.py", line 711, in open_file
    self.ui.pool_widget.refresh()
  File "/usr/lib/python2.7/dist-packages/libqtopensesame/widgets/pool_widget.py", line 179, in refresh
    icon = self.theme.qfileicon(self.pool[path])
  File "/usr/lib/python2.7/dist-packages/libqtopensesame/misc/theme.py", line 114, in qfileicon
    fileinspector.translate_to_xdg(fileinspector.determine_type(path)),
  File "/usr/lib/python2.7/dist-packages/fileinspector.py", line 196, in translate_to_xdg
    return mimetype.replace("/","-")
AttributeError: 'bool' object has no attribute 'replace'
```

**Comment by dschreij** [comment]
That’s weird. I solved that one twice already…
I’ll look into it!

**Comment by smathot** [comment]
My bad.
